CREATE TABLE IF NOT EXISTS "Users" (
  id SERIAL PRIMARY KEY,
  user_name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "Devices" (
  id SERIAL PRIMARY KEY,
  device_name VARCHAR(255) NOT NULL,
  serial_number VARCHAR(255) UNIQUE NOT NULL,
  user_name VARCHAR(255)
);
